@ECHO OFF

REM Define path to directory with compiled SWIG Python wrapper for FMI++ import library (Release mode).
SET FMIPPIM_SWIG_DIR=D:\Development\fmipp\msvc\import\swig

REM Define path to directory with compiled FMI++ import library (Release mode).
SET FMIPPIM_DLL_DIR=D:\Development\fmipp\msvc\Release

REM Define path to directory with compiled SUNDIALS libraries.
SET SUNDIALS_LIB_DIR=D:\Tools\sundials-2.5.0\lib32_msvc-10.0

REM Define path to directory with additional FMI++ Python scripts.
SET FMIPP_SCRIPTS_DIR=D:\Development\fmipp\scripts

REM ##################################################################################################
REM ##################################################################################################

REM Path to binary dir of FMI++ Python Interface.
SET PY_FMIPP_DIR=%~DP0\fmipp

REM Copy Python wrapper generated by SWIG.
COPY "%FMIPPIM_SWIG_DIR%\fmippim.py" "%PY_FMIPP_DIR%"

REM Copy Python wrapper library generated by SWIG.
COPY "%FMIPPIM_SWIG_DIR%\Release\_fmippim.pyd" "%PY_FMIPP_DIR%\lib"

REM Copy FMI++ import library DLL.
COPY "%FMIPPIM_DLL_DIR%\fmippim.dll" "%PY_FMIPP_DIR%\lib"

REM Copy SUNDIALS libraries.
COPY "%SUNDIALS_LIB_DIR%\sundials_cvode.dll" "%PY_FMIPP_DIR%\lib"
COPY "%SUNDIALS_LIB_DIR%\sundials_nvecserial.dll" "%PY_FMIPP_DIR%\lib"

REM Copy additional Python scripts from FMI++.
XCOPY /y /v "%FMIPP_SCRIPTS_DIR%\*.py" "%PY_FMIPP_DIR%"

REM Create self-installer for FMI++ Python Interface.
python.exe "%~DP0\setup.py" bdist_wininst --no-target-compile --no-target-optimize --title "FMI++ Python Interface for Windows" --bitmap logo\logo_py_fmipp.bmp

REM Clean up.
REM RD /S build