@ECHO OFF

REM Define path to directory with compiled SWIG Python wrapper for FMI++ import library (Release mode).
SET FMIPPIM_SWIG_DIR=D:\Development\fmipp\msvc\import\swig

REM Define path to directory with compiled FMI++ import library (Release mode).
SET FMIPPIM_DLL_DIR=D:\Development\fmipp\msvc\Release

REM Define path to directory with compiled SUNDIALS libraries.
SET SUNDIALS_LIB_DIR=D:\Tools\sundials-2.5.0\lib32_msvc-10.0

REM Path to binary dir of FMI++ Python Wrapper.
SET PY_FMIPP_DIR=%~DP0\fmipp

REM Copy Python wrapper generated by SWIG.
CP "%FMIPPIM_SWIG_DIR%\fmippim.py" "%PY_FMIPP_DIR%"

REM Copy Python wrapper library generated by SWIG.
CP "%FMIPPIM_SWIG_DIR%\Release\_fmippim.pyd" "%PY_FMIPP_DIR%\lib"

REM Copy FMI++ import library DLL.
CP "%FMIPPIM_DLL_DIR%\fmippim.dll" "%PY_FMIPP_DIR%\lib"

REM Copy SUNDIALS libraries.
CP "%SUNDIALS_LIB_DIR%\sundials_cvode.dll" "%PY_FMIPP_DIR%\lib"
CP "%SUNDIALS_LIB_DIR%\sundials_nvecserial.dll" "%PY_FMIPP_DIR%\lib"

REM Create self-installer for FMI++ Python Wrapper.
python.exe "%~DP0\release.py" bdist_wininst